/* Do not edit - Machine generated */
#ifndef _INC_MERGEOS_BUILDNO
#define _INC_MERGEOS_BUILDNO

#define KERNEL_VERSION_BUILD        @KERNEL_VERSION_BUILD@
#define KERNEL_VERSION_BUILD_STR    "@KERNEL_VERSION_BUILD@-@REVISION@"
#define KERNEL_VERSION_BUILD_RC     "@KERNEL_VERSION_BUILD@-@REVISION@\0"

#define KERNEL_VERSION_RC           "@KERNEL_VERSION@\0"
#define KERNEL_VERSION_STR          "@KERNEL_VERSION@"

#define KERNEL_VERSION_REVISION_RC  "@REVISION@\0"
#define KERNEL_VERSION_REVISION_STR "@REVISION@"

#define KERNEL_VERSION_COMMIT_HASH  "@COMMIT_HASH@"

#define MERGEOS_DLL_VERSION_MAJOR   @MERGEOS_DLL_VERSION_MAJOR@
#define MERGEOS_DLL_VERSION_RC      "@DLL_VERSION_STR@\0"
#define MERGEOS_DLL_VERSION_STR     "@DLL_VERSION_STR@"

#define MERGEOS_COMPILER_NAME       "@CMAKE_C_COMPILER_ID@"
#define MERGEOS_COMPILER_VERSION    "@CMAKE_C_COMPILER_VERSION@"

#endif
/* EOF */
